//go:build ignore

package main

import (
	"flag"
	"fmt"
	"io"
	"os"
)

const (
	licPrefix = `// NOTE: Code generated by go generate; DO NOT EDIT.

package main

import (
	"os"
)

func printLicense() {
	os.Stdout.WriteString(license)
	os.Exit(0)
}

const license = `

	licPostfix = `
`
)

func main() {

	inFile := flag.String("in", "", "infile")
	outFile := flag.String("out", "", "outfile")
	flag.Parse()

	ow, ir := os.Stdout, os.Stdin

	if *inFile != "" {
		ir, _ = os.Open(*inFile)
		defer ir.Close()
	}

	if *outFile != "" {
		ow, _ = os.Create(*outFile)
		defer ow.Close()
	}

	fmt.Fprint(ow, licPrefix)
	fmt.Fprint(ow, "`")
	io.Copy(ow, ir)
	fmt.Fprint(ow, "`")
	fmt.Fprint(ow, licPostfix)
}
